run:
  tests: false
  timeout: 5m
  skip-dirs:
    - crawlwer/fixtures
linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - depguard
    - dogsled
    - durationcheck
    - errcheck
    - errname
    - exhaustive
    - exportloopref
    - forcetypeassert
    - funlen
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofmt
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - ireturn
    - lll
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tenv
    - testpackage
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace
    - wsl
  disable:
    - gofumpt
    - thelper
    - forbidigo
    - gomnd
    - gci
    - dupl
    - tagliatelle
    # In issue error handling move to enable.
    - wrapcheck
    - errorlint
    - goerr113
    - goimports
    - revive
    - gochecknoglobals
    - varnamelen
    - exhaustivestruct
    - deadcode
    - varcheck
    - structcheck
    - ifshort
    - cyclop
